FROM docker:latest

# Based on https://github.com/Ilhicas/alpine-pipenv
ARG packages
RUN apk --update add python3 python3-dev gcc make \
        musl-dev libffi-dev openssl-dev ${packages} \
    && rm -rf /var/cache/apk/* \
    && pip3 install -U pip pipenv


# -v "$(pwd):/ws" your workspace at runtime
RUN set -ex && mkdir /ws
WORKDIR /ws
ENV PIPENV_CACHE_DIR /ws/.pipenv

RUN echo "set -ex && pipenv install --system && sh /ws/Dockerfile.sh && \$@" > /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT entrypoint.sh
