FROM docker:latest

# Based on https://github.com/Ilhicas/alpine-pipenv
ARG packages
RUN apk --update add python3 python3-dev gcc make \
        musl-dev libffi-dev openssl-dev ${packages} \
    && rm -rf /var/cache/apk/* \
    && pip3 install -U pip pipenv


# -v "$(pwd):/app" your workspace at runtime
RUN set -ex && mkdir /app
WORKDIR /app
ENV PIPENV_CACHE_DIR /app/.pipenv

RUN echo "set -ex && pipenv install --system && sh /app/Dockerfile.sh && \$@" > /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT entrypoint.sh
